# Generated by Django 5.1.2 on 2025-01-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_score_user1_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user1_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='score',
            name='user2_id',
            field=models.CharField(max_length=255),
        ),
    ]
