# Generated by Django 5.1.2 on 2025-01-11 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_games_delete_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='games',
            new_name='pongames',
        ),
    ]
